= OpenShift on Red Hat Enterprise Virtualization


== Standard RHEL9 install

=== Create a Openshift User with admin priviledges

=== Add Virtualization

dnf install qemu-kvm libvirt virt-install virt-viewer cockpit-machines wget podman nmstate
for drv in qemu network nodedev nwfilter secret storage interface; do systemctl start virt${drv}d{,-ro,-admin}.socket; done
virt-host-validate

=== Fix boot parameters - depending on CPU

=== Intel
intel_iommu=on

    grubby –update-kernel=ALL –args=”intel_iommu=on"

=== Enable Nested virtualization for Openshift Virtualization
/etc/modprobe.d/kvm.conf

		options kvm_intel nested=1

== Environment

=== SELINUX
[source]
----
sudo -i -- <<EOC
semanage import <<EOF
boolean -D
login -D
interface -D
user -D
port -D
node -D
fcontext -D
module -D
ibendport -D
ibpkey -D
permissive -D
boolean -m -1 virt_sandbox_use_all_caps
boolean -m -1 virt_use_nfs
permissive -a insights_client_t
permissive -a rhcd_t
EOF
EOC


=== OpenVSwitch

[source]
----
#wget https://www.openvswitch.org/releases/openvswitch-3.1.2.tar.gz
#fast-datapath-for-rhel-9-x86_64-rpms
#dnf provides ovs-vsctl

subscription-manager repos --enable fast-datapath-for-rhel-9-x86_64-rpms
dnf install openvswitch3.0
systemctl enable --now openvswitch
ovs-vsctl add-br ovsbr0
cd ~
mkdir -p openshift/{vms,install,mirror,downloads}
cd openshift/vms
cat <<EON > ovs-network.xml
<network>
  <name>vm-network</name>
  <uudi>$(uuidgen)</uudi>
  <forward mode="bridge"/>
  <bridge name="ovsbr0"/>
  <virtualport type='openswitch'/>
</network>
EON
virsh net-define ovs-network
virsh net-autostart ovs
virsh net-start

----

=== Add env variables to keep track of settings

[source]
----
cd ~
mkdir .bashrc.d
cat <<EOF > .bashrc.d/openshift.env
#/bin/bash
export QUAY_HOSTNAME=$(hostname -f)
export QUAY_USER=quay
export QUAY_PASSWORD=quayquay
export OCP_BASEDOMAIN=pietersmalan.com
export OCP_CLUSTERNAME=ocp
export OCP_CLUSTERMACHINE=$(ip addr show |grep -w inet |grep -v 127.0.0.1|awk '{ print $4}'|sed "s/255/0/g"|head -n1)
export OCP_CLUSTERMACHINECIDR=${OCP_CLUSTERMACHINE}/$(ip addr show |grep -w inet |grep -v 127.0.0.1|awk '{ print $2}'| cut -d "/" -f 2|head -n1)
export OCP_CLUSTERAPI=$(dig +short api.${OCP_CLUSTERNAME}.${OCP_BASEDOMAIN})
export OCP_CLUSTERINGRESS=$(dig +short x.apps.${OCP_CLUSTERNAME}.${OCP_BASEDOMAIN})
EOF
. ~/.bashrc.d/openshift.env
----

== Create Openshift Install artifacts

[source]
----
cd ~
mkdir -p openshift/{vms,install,mirror,downloads}
cd openshift/vms

virsh net-define ${PWD}/kvmbridge.xml
virsh net-start host-bridge
virsh net-autostart host-bridge

qemu-img create ocp1_os 120G
qemu-img create ocp2_os 120G
qemu-img create ocp3_os 120G
virt-install --name ocp1 --memory 16384 --vcpus 8 --boot hd,cdrom --disk ocp1_os --import --os-variant rhel9.2 --noreboot --cpu host --boot uefi --rng /dev/random --network type=direct,source=bond0,source_mode=bridge,model=virtio
virt-install --name ocp2 --memory 16384 --vcpus 8 --boot hd,cdrom --disk ocp2_os --import --os-variant rhel9.2 --noreboot --cpu host --boot uefi --rng /dev/random --network type=direct,source=bond0,source_mode=bridge,model=virtio
virt-install --name ocp3 --memory 16384 --vcpus 8 --boot hd,cdrom --disk ocp3_os --import --os-variant rhel9.2 --noreboot --cpu host --boot uefi --rng /dev/random --network type=direct,source=bond0,source_mode=bridge,model=virtio
----

=== Openshift - binaries

[source]
----
cd ~/openshift/downloads
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
ls *tar.gz | xargs -n 1 tar -zxvf
mkdir ~/bin
mv oc kubectl openshift-install ~/bin
wget https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz
----

== Certificates and pull-secret

[source]
----
cd ~/install
// pull-secret.txt from console.redhat.com/openshift/downloads
// Certificate for rhel9 host "full chain"(or wildcard for rhel9 host domain) cert/key
// reg.pem
// regkey.pem
----   
    
== Mirror Registry
    

=== Mirror Registry Install

[source]
----
cd ~/openshift/mirror
tar zxvf downloads/mirror-registry.tar.gz
ssh-keygen
ssh-copy-id $QUAY_HOSTNAME
sudo cp ../install/reg.pem /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust
# Not sure if required
sudo ausearch -c 'lsmd' --raw | audit2allow -M my-lsmd
sudo semodule -X 300 -i my-lsmd.pp
sudo ./mirror-registry install --initUser $QUAY_USER --initPassword $QUAY_PASSWORD --quayHostname ${QUAY_HOSTNAME} --sslCert ../install/reg.pem --sslKey ../install/regkey.pem
sudo firewall-cmd --add-port=8443/tcp --zone=public --permanent
sudo firewall-cmd --reload

----
     
=== Populate Mirror Registry (Online)

[source]
----

cd ~/openshift/mirror
OCP_RELEASE=$(openshift-install version|awk -F ' ' '{print $2}'|head -n 1)
LOCAL_REGISTRY=${QUAY_HOSTNAME}:8443
LOCAL_REPOSITORY='quay/ocp'
cat ../install/pull-secret.txt | jq . > pull-secret.json
cp pull-secret.json ${XDG_RUNTIME_DIR}/containers/auth.json
podman login --username $QUAY_USER --password $QUAY_PASSWORD $QUAY_HOSTNAME:8443
cp ${XDG_RUNTIME_DIR}/containers/auth.json pull-secret.json
LOCAL_SECRET_JSON='pull-secret.json'
PRODUCT_REPO='openshift-release-dev'
RELEASE_NAME='ocp-release'
ARCHITECTURE=x86_64
REMOVABLE_MEDIA_PATH=$PWD/dump/

# Example to extract to local directory, to dump the images, transfer and use following command on remote to import
#oc adm release mirror -a ${LOCAL_SECRET_JSON} --to-dir=${REMOVABLE_MEDIA_PATH}/mirror quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE}

# Example to upload images from local directory, in the case of total disconnected install
#oc image mirror -a ${LOCAL_SECRET_JSON} --from-dir=${REMOVABLE_MEDIA_PATH}/mirror "file://openshift/release:${OCP_RELEASE}*" ${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}

# Registry to Registry mirror process
oc adm release mirror -a ${LOCAL_SECRET_JSON} --from=quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE} --to=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY} --to-release-image=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}

#oc adm release extract -a ${LOCAL_SECRET_JSON} --command=openshift-install "${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}"
----

== OpenShift Install

[source]
----
cd ~/openshift/install
rm -Rf agent* auth cluster-manifests/ mirror/ manifests/ mirror/ openshift/ pull-secret.json rendezvousIP  .openshift_install.log
cat ../install/pull-secret.txt | jq . > pull-secret.json
cp pull-secret.json ${XDG_RUNTIME_DIR}/containers/auth.json
podman login --username $QUAY_USER --password $QUAY_PASSWORD $QUAY_HOSTNAME:8443
cp ${XDG_RUNTIME_DIR}/containers/auth.json pull-secret.json
export SECRET=pull-secret.json
cat <<EOF > install-config.yaml
additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: ${OCP_BASEDOMAIN}
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    baremetal: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    baremetal: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: ${OCP_CLUSTERNAME}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: ${OCP_CLUSTERMACHINECIDR}
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIPs:
    - ${OCP_CLUSTERAPI}
    ingressVIPs:
    - ${OCP_CLUSTERINGRESS}
    hosts:
    - bmc:
        address: ""
        disableCertificateVerification: false
        password: ""
        username: ""
      name: ocp1.${OCP_BASEDOMAIN}
      role: master
      bootMACAddress: $(echo $(virsh dumpxml ocp1 | grep -Eo "mac address='(.*?)'")| cut -d"'" -f 2)
      bootMode: UEFI
    - bmc:
        address: ""
        disableCertificateVerification: false
        password: ""
        username: ""
      name: ocp2.${OCP_BASEDOMAIN}
      role: master
      bootMACAddress: $(echo $(virsh dumpxml ocp2 | grep -Eo "mac address='(.*?)'")| cut -d"'" -f 2)
      bootMode: UEFI
    - bmc:
        address: ""
        disableCertificateVerification: false
        password: ""
        username: ""
      name: ocp3.${OCP_BASEDOMAIN}
      role: master
      bootMACAddress: $(echo $(virsh dumpxml ocp3 | grep -Eo "mac address='(.*?)'")| cut -d"'" -f 2)
      bootMode: UEFI
      libvirtURI: qemu:///system
      provisioningMACAddress: 52:54:00:ce:1a:21
      provisioningNetwork: Disabled
      provisioningNetworkInterface: ""
publish: External
pullSecret: '$(cat pull-secret.json |jq -c .)'
sshKey: |
  $(cat ~/.ssh/id_rsa.pub)
imageContentSources:
- mirrors:
  - ${QUAY_HOSTNAME}:8443/quay/ocp
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - ${QUAY_HOSTNAME}/quay/ocp
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev

EOF

#openshift-install create manifests

#cat <<EOF > openshift/99_openshift_cluster-imageDigestMirrorSet.yaml
#apiVersion: config.openshift.io/v1
#kind: ImageDigestMirrorSet
#metadata:
#  name: oc-mirror
#spec:
#  imageDigestMirrors:
#    - mirrorSourcePolicy: AllowContactingSource
#      mirrors:
#        - '${QUAY_HOSTNAME}:8443'
#      source: registry.redhat.io
#    - mirrorSourcePolicy: AllowContactingSource
#      mirrors:
#        - '${QUAY_HOSTNAME}:8443'
#      source: quay.io
#EOF

#cat <<EOF > openshift/99_openshift_cluster-imageTagMirrorSet.yaml
#apiVersion: config.openshift.io/v1
#kind: ImageTagMirrorSet
#metadata:
#  name: oc-mirror
#spec:
#  imageTagMirrors:
#    - mirrorSourcePolicy: AllowContactingSource
#      mirrors:
#        - '${QUAY_HOSTNAME}:8443'
#      source: registry.redhat.io
#    - mirrorSourcePolicy: AllowContactingSource
#      mirrors:
#        - '${QUAY_HOSTNAME}:8443'
#      source: quay.io
#EOF

cat <<EOF > agent-config.yaml
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: ${OCP_CLUSTERNAME}
  namespace: ${OCP_CLUSTERNAME}
rendezvousIP: $(dig +short ocp1.${OCP_BASEDOMAIN})
hosts:
  - hostname: ocp1
    role: master
    interfaces:
      - name: enp1s0
        macAddress: $(echo $(virsh dumpxml ocp1 | grep -Eo "mac address='(.*?)'")| cut -d"'" -f 2)
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          mac-address: $(echo $(virsh dumpxml ocp1 | grep -Eo "mac address='(.*?)'")| cut -d"'" -f 2)
          ipv4:
            enabled: true
            address:
              - ip: $(dig +short ocp1.${OCP_BASEDOMAIN})
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - $(ip addr show |grep -w inet |grep -v 127.0.0.1|awk '{ print $4}'|sed "s/255/1/g"|head -n1)
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: $(ip addr show |grep -w inet |grep -v 127.0.0.1|awk '{ print $4}'|sed "s/255/1/g"|head -n1)
            next-hop-interface: enp1s0
            table-id: 254
  - hostname: ocp2
    role: master
    interfaces:
      - name: enp1s0
        macAddress: $(echo $(virsh dumpxml ocp2 | grep -Eo "mac address='(.*?)'")| cut -d"'" -f 2)
    networkConfig:
      interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          mac-address: $(echo $(virsh dumpxml ocp2 | grep -Eo "mac address='(.*?)'")| cut -d"'" -f 2)
          ipv4:
            enabled: true
            address:
              - ip: $(dig +short ocp2.${OCP_BASEDOMAIN})
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - $(ip addr show |grep -w inet |grep -v 127.0.0.1|awk '{ print $4}'|sed "s/255/1/g"|head -n1)
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: $(ip addr show |grep -w inet |grep -v 127.0.0.1|awk '{ print $4}'|sed "s/255/1/g"|head -n1)
            next-hop-interface: enp1s0
            table-id: 254
  - hostname: ocp3
    role: master
    interfaces:
      - name: enp1s0
        macAddress: $(echo $(virsh dumpxml ocp3 | grep -Eo "mac address='(.*?)'")| cut -d"'" -f 2)
    networkConfig:
      interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          mac-address: $(echo $(virsh dumpxml ocp3 | grep -Eo "mac address='(.*?)'")| cut -d"'" -f 2)
          ipv4:
            enabled: true
            address:
              - ip: $(dig +short ocp3.${OCP_BASEDOMAIN})
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - $(ip addr show |grep -w inet |grep -v 127.0.0.1|awk '{ print $4}'|sed "s/255/1/g"|head -n1)
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: $(ip addr show |grep -w inet |grep -v 127.0.0.1|awk '{ print $4}'|sed "s/255/1/g"|head -n1)
            next-hop-interface: enp1s0
            table-id: 254
EOF

#mkdir cluster-manifests

#cat << EOF > cluster-manifests/pull-secret.yaml
#apiVersion: v1
#kind: Secret
#type: kubernetes.io/dockerconfigjson
#metadata:
#  name: pull-ztp-${OCP_CLUSTERNAME}
#  namespace: ${CLUSTERNAME}
#stringData:
#  .dockerconfigjson: '$(cat pull-secret.json |jq -c .)'
#EOF

#mkdir mirror
#cat <<EOF > mirror/registries.conf
#[[registry]]
#  prefix = ""
#  location = "quay.io/openshift-release-dev/ocp-release"

#  [[registry.mirror]]
#    location = "${QUAY_HOSTNAME}:8443/quay/ocp"

#[[registry]]
#  prefix = ""
#  location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"

#  [[registry.mirror]]
#    location = "bastion.pietersmalan.com:8443/quay/ocp"
#EOF

#cp reg.pem mirror/ca-bundle.crt

rm -Rf .openshift*
#openshift-install agent create cluster-manifests
openshift-install agent create image

----

== Create Cluster

[source]
----
cd ~
cp openshift/install/agent.x86_64.iso /tmp
sudo -i -- <<EOF

mv /tmp/agent.x86_64.iso /root/openshift/vms
cd /root/openshift/vms
chown oug+rw *
virsh attach-disk ocp1 /root/openshift/vms/agent.x86_64.iso sdb --driver qemu --type cdrom --mode readonly --config
virsh attach-disk ocp2 /root/openshift/vms/agent.x86_64.iso sdb --driver qemu --type cdrom --mode readonly --config
virsh attach-disk ocp3 /root/openshift/vms/agent.x86_64.iso sdb --driver qemu --type cdrom --mode readonly --config
virsh start ocp1
virsh start ocp2
virsh start ocp3
EOF

----
