= openshift-kvm

== Standard RHEL9 install

=== Create a Openshift User with admin priviledges

=== Add Virtualization

dnf install qemu-kvm libvirt virt-install virt-viewer cockpit-machines wget podman 
for drv in qemu network nodedev nwfilter secret storage interface; do systemctl start virt${drv}d{,-ro,-admin}.socket; done
virt-host-validate

=== Fix boot parameters - depending on CPU

=== Intel
intel_iommu=on

    grubby –update-kernel=ALL –args=”intel_iommu=on"

=== Enable Nested virtualization for Openshift Virtualization
/etc/modprobe.d/kvm.conf

		options kvm_intel nested=1

== Environment

=== Add env variables to keep track of settings

[source]
----
cd ~
mkdir .bashrc.d
cat <<EOF >> .bashrc.d/openshift.env
#/bin/bash
export QUAY_HOSTNAME=$(hostname -f)
export QUAY_USER=quay
export QUAY_PASSWORD=quayquay
EOF

----

== Create VMS and Openshift Install artifacts

=== Virtual Machines

[source]
----
cd ~
mkdir -p openshift/{vms,install,mirror,downloads}
cd openshift/vms
qemu-img create node1_os 120G
qemu-img create node2_os 120G
qemu-img create node3_os 120G
virt-install --name node1 --memory 16384 --vcpus 8 --disk node1_os --import --os-variant rhl9 --noreboot
virt-install --name node2 --memory 16384 --vcpus 8 --disk node2_os --import --os-variant rhl9 --noreboot
virt-install --name node3 --memory 16384 --vcpus 8 --disk node3_os --import --os-variant rhl9 --noreboot
----

=== Openshift - binaries

[source]
----
cd ~/openshift/downloads
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
ls *tar.gz | xargs -n 1 tar -zxvf
mkdir ~/bin
mv oc kubectl openshift-install ~/bin
wget https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz
----

== Certificates and pull-secret

[source]
----
cd ~/install
// pull-secret.txt from console.redhat.com/openshift/downloads
// Certificate for rhel9 host "full chain"(or wildcard for rhel9 host domain) cert/key
// reg.pem
// regkey.pem
----   
    
== Setup Mirror
    

=== Mirror Registry

[source]
----
cd ~/openshift/mirror
tar zxvf downloads/mirror-registry.tar.gz
ssh-keygen
ssh-copy-id $QUAY_HOSTNAME
sudo ./mirror-registry install --initUser $QUAY_USER --initPassword $QUAY_PASSWORD --quayHostname ${QUAY_HOSTNAME} --sslCert ../install/reg.pem --sslKey ../install/regkey.pem
sudo firewall-cmd --add-port=8443/tcp --zone=public --permanent
sudo firewall-cmd --reload
----
     
=== Populate Mirror Registry (Online)

[source]
----
cd ~/openshift/mirror
OCP_RELEASE=$(openshift-install version|awk -F ' ' '{print $2}'|head -n 1)
LOCAL_REGISTRY=${QUAY_HOSTNAME}:8443
LOCAL_REPOSITORY='quay/ocp'
cat ../install/pull-secret.txt | jq . > pull-secret.json
cp pull-secret.json ${XDG_RUNTIME_DIR}/containers/auth.json
podman login --username $QUAY_USER --password $QUAY_PASSWORD $QUAY_HOSTNAME:8443
cp ${XDG_RUNTIME_DIR}/containers/auth.json pull-secret.json
LOCAL_SECRET_JSON='pull-secret.json'
PRODUCT_REPO='openshift-release-dev'
RELEASE_NAME='ocp-release'
ARCHITECTURE=x86_64
REMOVABLE_MEDIA_PATH=$PWD/dump/

# Example to extract to local directory, to dump the images, transfer and use following command on remote to import
#oc adm release mirror -a ${LOCAL_SECRET_JSON} --to-dir=${REMOVABLE_MEDIA_PATH}/mirror quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE}

# Example to upload images from local directory, in the case of total disconnected install
#oc image mirror -a ${LOCAL_SECRET_JSON} --from-dir=${REMOVABLE_MEDIA_PATH}/mirror "file://openshift/release:${OCP_RELEASE}*" ${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}

# Registry to Registry mirror process
oc adm release mirror -a ${LOCAL_SECRET_JSON} --from=quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE} --to=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY} --to-release-image=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}

#oc adm release extract -a ${LOCAL_SECRET_JSON} --command=openshift-install "${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}"
----
            
